#!/usr/bin/env python3
"""Generate dashboard/luma-dashboard.html from the live repo (.ai/index.json + files).

Regenerate after any structural change so the dashboard cannot drift into fiction.
"""
import json, os, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def P(*a): return os.path.join(ROOT, *a)
IDX = json.load(open(P(".ai", "index.json")))
AG  = {a["name"]: a for a in IDX["agents"]}

# the index truncates descriptions for context economy; the dashboard needs them whole
import re as _re
for _n, _a in AG.items():
    _t = open(P(_a["file"]), encoding="utf-8").read()
    _m = _re.search(r"^description:\s*(.+)$", _t, _re.M)
    if _m:
        _a["trigger"] = _m.group(1).strip()
ST  = IDX["state"]

def agent_node(name, layer, phase_note, reads, writes, gate, autonomy):
    a = AG[name]
    return {
        "id": name, "label": name, "kind": "agent", "layer": layer,
        "summary": phase_note,
        "detail": a["trigger"],
        "where": a["file"],
        "meta": [["model", a["model"]], ["tools", ", ".join(a["tools"])],
                 ["can write", "yes" if a["writes"] else "NO — read-only"],
                 ["autonomy", autonomy], ["gate", gate]],
        "reads": reads, "writes": writes,
    }

# ══════════════════ TAB 1 — WORKFLOW ══════════════════
W_LAYERS = [
    ("docs",  "Docs & automation",  "Rules, documentation, CI. Layer one — not an afterthought.", 232),
    ("p1",  "Phase 1 · Research",      "Raw sources become evidence.", 187),
    ("p2",  "Phase 2 · Define",        "Evidence becomes framing.", 187),
    ("p3",  "Phase 3 · Ideation",      "Framing becomes structure.", 265),
    ("p4",  "Phase 4 · Design",        "Structure becomes interface.", 38),
    ("p5",  "Phase 5 · Test",          "Interface meets users.", 340),
    ("p6",  "Phase 6 · Handoff",       "Design becomes buildable.", 340),
    ("p78", "Phase 7–8 · Impl. & QA",  "Build is measured against design.", 12),
    ("p9",  "Phase 9 · Launch",        "It ships, and is explained.", 150),
    ("p10", "Phase 10 · Monitor",      "Reality is measured.", 150),
    ("p11", "Phase 11 · Improve",      "Findings loop back to Phase 1.", 150),
]
W_NODES = [
 {"id":"claude-md","label":"CLAUDE.md","kind":"doc","layer":"docs",
  "summary":"The plan and the rules. Read at every session start.",
  "detail":"Loaded on every turn, so it stays short and points to files for detail. Holds the two prohibitions, the routing table, the gates, the autonomy ladder and the boundaries. Detail lives in agent definitions and the sources of truth, not here.",
  "where":"CLAUDE.md","meta":[["loaded","every turn"],["layer","5 — written"]],"reads":[],"writes":[]},
 {"id":"architecture-md","label":"architecture.md","kind":"doc","layer":"docs",
  "summary":"The map. What the parts are and how they relate.",
  "detail":"CLAUDE.md operates the system; architecture.md explains it. Contains the six-layer diagram, the work-flow trace, and a table naming which file implements which enforcement layer — so a future empty layer is visible.",
  "where":"architecture.md","meta":[["added","ADR-008"]],"reads":[],"writes":[]},
 {"id":"index-md","label":".ai/index.md","kind":"index","layer":"docs",
  "summary":"Generated index. Load once at session start, fetch detail on demand.",
  "detail":f"The indexing layer. {IDX['counts']['agents']} agents, {IDX['counts']['artifact_types']} artifact types, {IDX['counts']['adrs']} ADRs, {IDX['counts']['relationships']} typed relationships. Pre-computed so agents never re-derive system structure. Regenerated by validation/index-luma.py; CI fails if stale.",
  "where":".ai/index.md","meta":[["generated by","validation/index-luma.py"],["relationships",str(IDX['counts']['relationships'])]],"reads":[],"writes":[]},
 {"id":"settings","label":"settings.json","kind":"gate","layer":"docs",
  "summary":"The tool gate. Enforcement layer 1 — impossible, not forbidden.",
  "detail":"permissions.deny / ask / allow, plus the PreToolUse hook wiring. Tool-gating outranks prohibition: the benchmark found it works where written rules do not. An agent that lacks a tool cannot misuse it.",
  "where":".claude/settings.json","meta":[["layer","1 — impossible"],["bypass","cannot"]],"reads":[],"writes":[]},
 {"id":"ci","label":"ci.yml","kind":"gate","layer":"docs",
  "summary":"Enforcement layer 3. Runs the whole-repo audit on every change.",
  "detail":"Validates every JSON source of truth, fails if either generated index is stale, then runs validation/audit-system.py. A local hook can be disabled; CI cannot. This layer was a sentence with no implementation until ADR-008.",
  "where":".github/workflows/ci.yml","meta":[["layer","3 — failed"],["bypass","admin only"]],"reads":[],"writes":[]},
 {"id":"orchestrator","label":"orchestrator","kind":"agent","layer":"docs",
  "summary":"The conductor. Reads the plan, dispatches one worker, checks the gate.",
  "detail":AG["orchestrator"]["trigger"],
  "where":".claude/agents/orchestrator.md",
  "meta":[["model",AG["orchestrator"]["model"]],["tools",", ".join(AG["orchestrator"]["tools"])],
          ["never","does design work, or passes artifact content between agents"],
          ["counts","the autonomy ladder — 3 clean → Auto, 1 hard fail → Draft"]],
  "reads":["claude-md","index-md"],"writes":[]},

 agent_node("evidence-clerk","p1","Extracts verbatim quotes into the ledger. Never interprets.",
            ["sources"],["ledger"],"B + A","Draft → Auto (structural check runs Auto from day one)"),
 {"id":"sources","label":"research/sources/","kind":"ssot","layer":"p1",
  "summary":"Raw inputs. Immutable. Never edited, never generated.",
  "detail":"Transcripts, recordings, exports. Write and Edit are denied at enforcement layer 1 so immutability is structural, not a convention. Read stays open — evidence-clerk must be able to read them.",
  "where":"research/sources/","meta":[["state",f"{ST['raw_sources']} files"],["deny","Write, Edit"]],"reads":[],"writes":[]},
 {"id":"ledger","label":"evidence-ledger.json","kind":"ssot","layer":"p1",
  "summary":"Upstream source of truth. One record per verbatim quote.",
  "detail":"Every claim in every downstream artifact resolves to an ID here. An unresolved [E-nnn] is stripped, not softened — Gate B blocks the write. This is what prevents an agent inventing a user.",
  "where":"research/evidence-ledger.json","meta":[["state",f"{ST['evidence_records']} records"],["gate","citations must resolve"]],"reads":[],"writes":[]},
 agent_node("research-synthesizer","p2","Interprets the ledger into personas, insights, problem statements.",
            ["ledger"],[],"A","Suggest only — never graduates"),
 agent_node("diagram-cartographer","p2","Journey and empathy maps. One actor per map.",
            ["ledger"],[],"A","Draft"),
 {"id":"diagram-cartographer-ia","label":"diagram-cartographer","kind":"agent","layer":"p3",
  "summary":"Same agent, later phase: sitemaps, taxonomies, user flows.",
  "detail":"In Phase 3 it reads the insight report rather than raw evidence. IA is a structural decision that shapes everything downstream, so a human signs off (Gate A).",
  "where":".claude/agents/diagram-cartographer.md",
  "meta":[["model",AG["diagram-cartographer"]["model"]],["gate","A"],["reads","insight-report, not raw sources"]],
  "reads":[],"writes":[]},
 {"id":"screen-producer-sketch","label":"screen-producer","kind":"agent","layer":"p3",
  "summary":"Sketches and concepts from the IA map.",
  "detail":"Widest agent in the system — sketch through prototype, with the production surface set by the DS fork. Flagged in ADR-002 as the most likely site of scope creep; the routing table makes a later split cheap.",
  "where":".claude/agents/screen-producer.md",
  "meta":[["model",AG["screen-producer"]["model"]],["tools",", ".join(AG["screen-producer"]["tools"])],["gate","B"],["risk","widest scope — watch for creep"]],
  "reads":[],"writes":[]},
 agent_node("screen-producer","p4","Wireframe → hi-fi → prototype, constrained by tokens and the index.",
            ["tokens","cindex"],[],"B → A","Draft"),
 agent_node("a11y-checker","p4","First filter, never the final verdict. Read-only.",
            [],[],"B","Auto from day one — verifiable, read-only"),
 agent_node("research-ops","p5","Test plans, moderator guides, clustered findings, RICE.",
            [],[],"A","Draft — severity is set by a human, not the agent"),
 agent_node("handoff-scribe","p6","Specs, redlines, acceptance criteria. The last gate before engineering.",
            ["cindex"],[],"A","Draft"),
 agent_node("design-critic","p78","Adversarial review from clean context. Advisory, not automatic.",
            [],[],"B (A on change)","Advisory — read-only is not zero blast radius"),
 agent_node("content-comms","p9","Release notes, launch comms, support docs. Public-facing gets a human.",
            [],[],"A","Draft"),
 agent_node("dashboard-analyst","p10","Dashboards and data visualisation from live connectors.",
            ["tokens"],[],"B","Draft"),
 {"id":"synth-improve","label":"research-synthesizer","kind":"agent","layer":"p11",
  "summary":"Prioritised roadmap and research hypotheses — then loops to Phase 1.",
  "detail":"The loop closes here. Metrics plus the ledger produce the next round of hypotheses, which become new research questions in Phase 1. This is why the Design Loop is cyclical while Build Stages are linear (ADR-004).",
  "where":".claude/agents/research-synthesizer.md",
  "meta":[["gate","A"],["autonomy","Suggest only — never graduates"],["next","→ Phase 1"]],
  "reads":[],"writes":[]},
]
W_EDGES = [
 ("orchestrator","evidence-clerk","dispatches"),("sources","evidence-clerk","reads"),
 ("evidence-clerk","ledger","writes"),("ledger","research-synthesizer","reads"),
 ("ledger","diagram-cartographer","reads"),("research-synthesizer","diagram-cartographer-ia","feeds"),
 ("diagram-cartographer-ia","screen-producer-sketch","feeds"),
 ("screen-producer-sketch","screen-producer","advances"),
 ("screen-producer","a11y-checker","gates"),("a11y-checker","research-ops","advances"),
 ("research-ops","handoff-scribe","advances"),("handoff-scribe","design-critic","advances"),
 ("design-critic","content-comms","advances"),("content-comms","dashboard-analyst","advances"),
 ("dashboard-analyst","synth-improve","advances"),("synth-improve","evidence-clerk","loops back"),
 ("claude-md","orchestrator","instructs"),("index-md","orchestrator","informs"),
 ("settings","orchestrator","constrains"),
]

# ══════════════════ TAB 2 — DESIGN SYSTEM ══════════════════
D_LAYERS = [
 ("fork","DS state fork","Decided at kickoff. CoForge is RED.",0),
 ("found","Foundations","Voice and visual language, before tokens encode anything.",280),
 ("tok","Tokenization","Values and definitions. You start building or auditing here.",38),
 ("comp","Components","Contracts for machines, intent for reasoning.",200),
 ("memb","The membrane","The only path into the design system.",355),
 ("bridge","Design ↔ code contract","Parity through durable keys.",232),
]
D_NODES = [
 {"id":"red","label":"RED — no DS","kind":"state","layer":"fork","summary":"Current state. token-keeper builds the system before screens are produced.",
  "detail":"screen-producer stays wireframe-only until tokens and the component index exist. This is not a limitation to work around — producing hi-fi UI with no system is exactly what creates off-system drift.",
  "where":"CLAUDE.md · DS fork","meta":[["current","yes"],["unblocks","Build Stage 2"]],"reads":[],"writes":[]},
 {"id":"yellow","label":"YELLOW — DS not in code","kind":"state","layer":"fork","summary":"System exists in Figma but not as code. Match, review, feed gaps back.",
  "detail":"screen-producer matches components to wireframes and reviews consistency; gaps route to token-keeper.","where":"CLAUDE.md · DS fork","meta":[["current","no"]],"reads":[],"writes":[]},
 {"id":"green","label":"GREEN — DS in code","kind":"state","layer":"fork","summary":"Most optimised route: generate against the real component library.",
  "detail":"screen-producer targets Claude Code + Figma MCP + Code Connect, generating against real components.","where":"CLAUDE.md · DS fork","meta":[["current","no"]],"reads":[],"writes":[]},
 {"id":"brand","label":"brand.md","kind":"doc","layer":"found","summary":"Voice, visual language, colour rationale, type scale logic, motion character.",
  "detail":"Owned by brand-director at suggest-only, and it never graduates. Brand direction is a judgment call — it is never written automatically, and never inferred from the absence of input. Currently a stub awaiting brand inputs.",
  "where":"design-system/foundations/brand.md","meta":[["owner","brand-director"],["autonomy","suggest only — never graduates"],["state","EMPTY" if not ST["brand_defined"] else "defined"]],"reads":[],"writes":[]},
 {"id":"tokens","label":"tokens.json","kind":"ssot","layer":"tok","summary":"DTCG format. The only legal source of colour, spacing, radius and type.",
  "detail":"Raw hex and raw px are a build error, not a style opinion. Gate B blocks the write and names the token to use instead. Currently empty — which is why the tokens check reports SKIPPED rather than PASSED.",
  "where":"design-system/tokens/tokens.json","meta":[["format","W3C DTCG"],["state",f"{ST['tokens']} tokens"],["gate","no value outside tokens"]],"reads":[],"writes":[]},
 {"id":"inversion","label":"ADR-001 inversion","kind":"gate","layer":"tok","summary":"Repo authors v0, pushes to Figma, then direction flips permanently.",
  "detail":"Greenfield means the repo must author first — there is nothing to read yet. The moment Figma variables exist, Figma owns tokens and the repo mirrors only. The drift check fails the build on divergence. A break-glass path to re-author exists but using it is a logged incident.",
  "where":"decisions/ADR-001-token-ssot.md","meta":[["before","repo authors"],["after","Figma owns, repo mirrors"],["reached","not yet"]],"reads":[],"writes":[]},
 {"id":"figvars","label":"Figma variables","kind":"ext","layer":"tok","summary":"Token owner after the inversion point.",
  "detail":"Designers change tokens in Figma. token-keeper exports them back down and the drift check enforces that the repo is a mirror, not a second author.",
  "where":"Figma · external","meta":[["owner after inversion","yes"],["tooling","figma-console export/import"]],"reads":[],"writes":[]},
 {"id":"cindex","label":"component-index.json","kind":"ssot","layer":"comp","summary":"The catalogue. Query before you invent.",
  "detail":"Machine-readable: props, variants, sizes, states, slots, a11y, tokens_used, when_to_use and when_not_to_use. A component absent from here cannot be used — Gate B blocks it and tells you to file a proposal instead.",
  "where":"design-system/component-index.json","meta":[["state",f"{ST['components']} components"],["gate","no component outside the index"]],"reads":[],"writes":[]},
 {"id":"cjson","label":"<Name>.json","kind":"artifact","layer":"comp","summary":"The contract — for machines.",
  "detail":"JSON for contracts is a measured decision, not a preference: structured metadata benchmarked at 80% fewer tokens and 5x lower annual cost than prose (Indeed, via ADR-006).",
  "where":"design-system/components/","meta":[["audience","agents"],["why JSON","~80% fewer tokens"]],"reads":[],"writes":[]},
 {"id":"cmd","label":"<Name>.md","kind":"doc","layer":"comp","summary":"The intent — and when NOT to use it.",
  "detail":"Markdown carries what reasoning needs: intent, nuance, and the negative case. The 'when not to use' section is the one that prevents misuse; a contract alone cannot express it.",
  "where":"design-system/components/","meta":[["audience","humans and reasoning"],["key section","when NOT to use"]],"reads":[],"writes":[]},
 {"id":"spec","label":"component-spec","kind":"artifact","layer":"memb","summary":"A PROPOSAL. It is not a component.",
  "detail":"Lives in artifacts/. Must state when not to use, and name the existing component it is not a duplicate of. Writing one does not modify the index.",
  "where":"artifacts/<ws>/…__component-spec__…/","meta":[["is","a proposal"],["is not","a component"]],"reads":[],"writes":[]},
 {"id":"promotion","label":"Promotion","kind":"gate","layer":"memb","summary":"Explicit human approval, recorded as an ADR. The only path in.",
  "detail":"Without this membrane, artifacts/ and design-system/ bleed into each other and the system accumulates one-off project work. Promotion is deliberate, human, and leaves a record.",
  "where":"decisions/","meta":[["requires","human approval + ADR"],["prevents","project work polluting the system"]],"reads":[],"writes":[]},
 {"id":"figmap","label":"figma-code-map.json","kind":"ssot","layer":"bridge","summary":"Figma property ↔ code prop ↔ token.",
  "detail":"The design-to-development contract. Populated at Build Stage 2. Code Connect lives only on the official Figma MCP, which is why handoff-scribe is chartered to it (ADR-007).",
  "where":"design-system/contracts/figma-code-map.json","meta":[["populated","Build Stage 2"],["tooling","Code Connect"]],"reads":[],"writes":[]},
 {"id":"a11yrules","label":"a11y/rules.md","kind":"doc","layer":"bridge","summary":"WCAG 2.2 AA floor. A PASS carries the computed value.",
  "detail":"Contrast 4.5:1 normal / 3:1 large, non-text 3:1, targets 24×24, focus always visible, placeholder is not a label, respect prefers-reduced-motion. 'Contrast 4.8:1 against a 4.5:1 threshold' is evidence; 'looks fine' is not.",
  "where":"design-system/a11y/rules.md","meta":[["floor","WCAG 2.2 AA"],["owner","a11y-checker"]],"reads":[],"writes":[]},
]
D_EDGES = [
 ("red","brand","starts at"),("brand","tokens","defines"),("tokens","inversion","reaches"),
 ("inversion","figvars","hands ownership to"),("figvars","tokens","mirrors back"),
 ("tokens","cindex","constrains"),("cindex","cjson","contains"),("cindex","cmd","documents"),
 ("spec","promotion","requires"),("promotion","cindex","enters"),
 ("cindex","figmap","maps"),("cjson","figmap","maps"),
]

# ══════════════════ TAB 3 — HARNESS & ANALYTICS ══════════════════
H_LAYERS = [
 ("loop","The agent loop","Every artifact runs this. No step is optional.",187),
 ("enf","Enforcement — hardest to softest","Every layer names the file that implements it.",355),
 ("aut","Autonomy ladder","Earned per task type, with evidence. It goes down as well as up.",38),
 ("gov","Governance & adoption","Guardrails live in the path of the work, and ship as software.",265),
 ("ana","Analytics","What gets measured, and how.",200),
]
_loop = [("consult","CONSULT","Query the index, ledger and tokens. Never work from memory.",
          "The indexing layer exists so this step is cheap. An agent that re-derives structure every session pays for it in tokens and in variance."),
         ("produce","PRODUCE","One agent, one artifact, into artifacts/.",
          "Narrow mandate. The agent writes only its declared output path — enforced by per-agent tool grants, not by instruction."),
         ("validate","VALIDATE","Checklist plus scripts. Severity-ranked, with suggested fixes.",
          "Hard fails: unresolved citation, raw hex, component not in the index, unregistered artifact type. Skipped checks are reported — skipped is not passed."),
         ("critique","CRITIQUE","design-critic attacks it from clean context. Read-only.",
          "Kept separate so the producing agent's rationale doesn't contaminate the review. Catches the plausible-but-wrong artifact that self-review misses."),
         ("present","PRESENT","The human sees the artifact and its validation report together.",
          "Never the artifact alone. The report is what makes 'it passed' checkable rather than asserted."),
         ("correct","CORRECT","The correction goes to memory/corrections.md with its reason.",
          "The reason matters more than the correction. Without it the rule is unmaintainable and gets deleted at the next review."),
         ("learn","LEARN","Same correction twice → promoted to a standing rule in CLAUDE.md.",
          "This is what makes the system compound instead of repeating itself.")]
H_NODES = [{"id":i,"label":l,"kind":"step","layer":"loop","summary":s,"detail":d,
            "where":"CLAUDE.md · the work loop","meta":[],"reads":[],"writes":[]} for i,l,s,d in _loop]
_enf = [("l1","1 · Impossible","Tool-gating — the agent lacks the tool.","cannot",".claude/settings.json + per-agent tools:",
         "The benchmark of 20 design systems found tool-gating outperforms prohibition, despite prohibition being more commonly used. Never solve with a permission what prose is being asked to do."),
        ("l2","2 · Blocked","PreToolUse hook rejects the write.","edit local config",".claude/hooks/gate-b.py",
         "Severity-ranked, every finding carries a fix, and skipped checks are named. Exempts scratch/ by design — failures belong somewhere."),
        ("l3","3 · Failed","The same validators run on every push and PR.","admin only",".github/workflows/ci.yml",
         "Was a sentence with no implementation until ADR-008. A named-but-empty layer is worse than an absent one, because it reads as coverage."),
        ("l4","4 · Visible","Severity-ranked audit report, published.","social","validation/reports/",
         "Drift you can see becomes drift someone fixes. Also the input to prioritisation — the top recurring findings are the roadmap."),
        ("l5","5 · Written","Two prohibitions in CLAUDE.md.","trivial","CLAUDE.md",
         "Deliberately only two: never invent a component, never invent a quote. Prose is the weakest instrument, so the list stays short.")]
H_NODES += [{"id":i,"label":l,"kind":"gate","layer":"enf","summary":s,"detail":d,"where":w,
             "meta":[["bypass",b],["implemented by",w]],"reads":[],"writes":[]} for i,l,s,b,w,d in _enf]
H_NODES += [
 {"id":"draft","label":"Draft","kind":"state","layer":"aut","summary":"Where everything that can write starts.",
  "detail":"Produces, but a human reviews before it counts. Gate A required.","where":"CLAUDE.md · autonomy ladder",
  "meta":[["default","yes"],["gate","A"]],"reads":[],"writes":[]},
 {"id":"auto","label":"Auto","kind":"state","layer":"aut","summary":"Earned after 3 consecutive clean reviews.",
  "detail":"Gate B only. The orchestrator counts, logging in memory/corrections.md. Two agents run Auto from day one — a11y-checker and evidence-clerk's structural check — because their output is verifiable and read-only.",
  "where":"memory/corrections.md","meta":[["requires","3 consecutive clean reviews"],["gate","B only"]],"reads":[],"writes":[]},
 {"id":"demote","label":"Demotion","kind":"gate","layer":"aut","summary":"One hard fail in Auto drops the task type back to Draft.",
  "detail":"The ladder only went up until ADR-002. A task type that graduated and then broke would have stayed Auto indefinitely — a real defect, closed by making the ladder bidirectional.",
  "where":"decisions/ADR-002-agent-roster.md","meta":[["trigger","1 hard fail"],["added","ADR-002"]],"reads":[],"writes":[]},
 {"id":"never","label":"Never graduates","kind":"state","layer":"aut","summary":"Brand direction and research conclusions. Always suggest-only.",
  "detail":"The clearest cases of decisions requiring human judgment. Also design-critic — advisory rather than automatic, because read-only is not zero blast radius when the output's purpose is to change what a human does next.",
  "where":"CLAUDE.md · autonomy ladder","meta":[["brand-director","suggest only"],["research conclusions","suggest only"],["design-critic","advisory"]],"reads":[],"writes":[]},
 {"id":"plugin","label":"Ship as a plugin","kind":"step","layer":"gov","summary":"Adoption becomes one install, not folder-copying that drifts.",
  "detail":"Agents, skills, settings and hooks packaged on an internal marketplace. Updating guardrails becomes one version bump that reaches everyone; auditing compliance becomes checking the installed version.",
  "where":"Build Stage 5","meta":[["adoption","one install"],["update","one version bump"]],"reads":[],"writes":[]},
 {"id":"escape","label":"Logged escape hatch","kind":"gate","layer":"gov","summary":"Every hard gate needs a one-step override that logs.",
  "detail":"The top reason guardrail programmes fail: a gate blocks legitimate work, people route around the system entirely, and all visibility is lost. With a logged override, exceptions become the roadmap — the top five each quarter are exactly what the design system is missing.",
  "where":"CLAUDE.md · guardrails","meta":[["prevents","shadow work"],["produces","compliance data"]],"reads":[],"writes":[]},
 {"id":"owner","label":"Every rule has an owner","kind":"step","layer":"gov","summary":"And a review date. A rule its owner can't defend is deleted.",
  "detail":"Rulesets that only grow get abandoned wholesale. Ownership plus a review date is what keeps the set small enough to be followed.",
  "where":"CLAUDE.md · guardrails","meta":[["prevents","ossification"]],"reads":[],"writes":[]},
 {"id":"onboard","label":"30-minute onboarding","kind":"step","layer":"gov","summary":"A hard acceptance criterion, not a nice-to-have.",
  "detail":"If a designer cannot produce something real within 30 minutes of installing, adoption dies regardless of how good the guardrails are.",
  "where":"Build Stage 5 gate","meta":[["type","gate to advance"]],"reads":[],"writes":[]},
 {"id":"telemetry","label":"Telemetry","kind":"index","layer":"ana","summary":"skill_activated · api_request · tool_decision · tool_result.",
  "detail":"CLAUDE_CODE_ENABLE_TELEMETRY=1 with OTLP export. Critically for org rollout: content capture is opt-in and off by default — prompts, responses and file contents stay dark, only skill, agent and tool names are visible. That is what makes a privacy review pass. For a small team, the JSONL session transcripts already on disk answer the same questions with no infrastructure.",
  "where":"not yet enabled","meta":[["status","method defined, not enabled"],["content capture","off by default"]],"reads":[],"writes":[]},
 {"id":"metrics","label":"Five portfolio metrics","kind":"index","layer":"ana","summary":"Activations · tokens per activation · cost per accepted artifact · abandon rate · co-activation.",
  "detail":"Zero activations in 90 days → archive. Top decile tokens → rewrite for progressive disclosure. High activated-but-abandoned → the description is wrong, not the body. Consistent co-activation → merge.",
  "where":"Build Stage 4","meta":[["archive rule","0 activations in 90 days"],["status","defined, no data yet"]],"reads":[],"writes":[]},
 {"id":"desc","label":"Description budget","kind":"gate","layer":"ana","summary":"The dominant token lever, and it is counterintuitive.",
  "detail":"Every skill's description loads into context permanently, on every turn; only the body loads on demand. Hundreds of skills with bloated descriptions burn tens of thousands of tokens before anyone types anything. Rewriting descriptions usually beats rewriting skills.",
  "where":"ADR-005","meta":[["limit","one line, trigger-focused"],["loads","every turn"]],"reads":[],"writes":[]},
 {"id":"evals","label":"Eval A/B delta","kind":"index","layer":"ana","summary":"Every case runs twice — with the skill and without.",
  "detail":"Without a baseline you cannot distinguish skill value from model capability. evals.json is the only hand-authored file; assertions are written AFTER the first run, because what 'good' looks like is not knowable until it has run. The benchmark delta — pass rate, time, tokens — is the keep-or-cut instrument.",
  "where":"decisions/ADR-005-skill-evals.md","meta":[["standard","agentskills.io"],["baseline","with vs without"],["assertions","written after first run"]],"reads":[],"writes":[]},
]
H_EDGES = [(_loop[i][0], _loop[i+1][0], "then") for i in range(len(_loop)-1)] + [
 ("learn","consult","informs next run"),("validate","l2","is"),("l2","l3","escalates to"),
 ("draft","auto","3 clean reviews"),("auto","demote","1 hard fail"),("demote","draft","returns to"),
 ("telemetry","metrics","feeds"),("metrics","evals","informs"),("evals","desc","tunes"),
]

DATA = {
 "generated": datetime.date.today().isoformat(),
 "state": ST, "counts": IDX["counts"],
 "adrs": IDX["adrs"],
 "tabs": [
   {"id":"workflow","label":"Workflow","blurb":"Eleven phases, thirteen agents, and the documents that govern them. Each phase names the agent that activates, what it reads, what it writes, and which gate it must clear.","layers":W_LAYERS,"nodes":W_NODES,"edges":W_EDGES,"numbered":True},
   {"id":"ds","label":"Design system","blurb":"The downstream half. Brand becomes tokens, tokens constrain components, and nothing enters the system except by promotion.","layers":D_LAYERS,"nodes":D_NODES,"edges":D_EDGES,"numbered":False},
   {"id":"harness","label":"Harness & analytics","blurb":"How the system holds itself honest: the loop every artifact runs, five enforcement layers, earned autonomy, and what gets measured.","layers":H_LAYERS,"nodes":H_NODES,"edges":H_EDGES,"numbered":False},
 ],
}
json.dump(DATA, open(P("dashboard","data.json"),"w"), indent=1)
print(f"data built: {sum(len(t['nodes']) for t in DATA['tabs'])} nodes, "
      f"{sum(len(t['edges']) for t in DATA['tabs'])} edges, {len(DATA['tabs'])} tabs")
