#!/usr/bin/env python3
"""
ART-026 v2 — Phase 0b. The theme field, audited the way Phase 0 audited confidence.

WHY THIS EXISTS
Phase 0 established that the `confidence` field could not be bucketed into three
categories without a mechanical audit, because doing so would be inference on
evidence. Two of v2's six charts -- ch-themes and ch-matrix -- bucket 121 `theme`
strings into 11 categories, and that field received no equivalent audit. Found by
design-critic, which also found the consequence: all three disruption findings
(F-56, F-107, F-113) are filed under `loyalty-and-retention`, so the matrix draws
Iberia x Disruption and Qatar x Disruption as EMPTY while this same board devotes a
whole figure to those exact two sweeps.

THE RULE, and its limits
Re-theming by hand would be inference and is not done here. What IS mechanical is
comparing two fields the record already contains: a finding's `theme`, and the
finding's own `id`, which the author wrote as a label for that finding. When an id
names theme X and the row is filed under theme Y, the record contradicts itself, and
that is visible without any judgement about which is right.

Scanned: ids only, never claim prose. Claim text mentions many themes in passing and
scanning it would produce judgement dressed as measurement. Ids are deliberate labels.

This produces a LOWER BOUND on disagreement. A mis-filed finding whose id happens to
name no theme is invisible to this check and is counted as unknown, not as agreeing.

Run:  python3 phase0b-theme-audit.py     Out: theme-audit.json
"""
import json, os, re, collections, datetime

HERE  = os.path.dirname(os.path.abspath(__file__))
ROUND = os.path.join(HERE, "..", "2026-09-04__competitive-benchmark__hands-on-capture-round-1__v1")

# Vocabulary is taken FROM THE THEME SLUGS THEMSELVES, plus morphological stems of
# those same words. No synonym is added -- adding "cancellation" to the disruption
# theme would be my judgement about what the theme covers, which is the thing this
# check must not do.
THEME_VOCAB = {
    "market-structure":         [r"market", r"structur"],
    "ranking-and-comparison":   [r"rank", r"compar", r"sort[_ ]?ax"],
    "price-honesty":            [r"price", r"pricing", r"honest"],
    "loyalty-and-retention":    [r"loyalt", r"retention", r"tier", r"genius", r"one[_ ]?key"],
    "disruption-and-protection":[r"disrupt", r"protect"],
    "decision-support":         [r"decision", r"support"],
    "trip-as-an-object":        [r"trip"],
    "user-types":               [r"user[_ ]?type"],
    "dark-patterns-and-trust":  [r"dark[_ ]?pattern", r"trust"],
    "method":                   [r"method", r"correction"],
    "other":                    [],
}

def themes_named_in(text):
    t = text.lower()
    return {th for th, pats in THEME_VOCAB.items()
            if pats and any(re.search(p, t) for p in pats)}

ci = json.load(open(os.path.join(ROUND, "CAPTURE-INDEX.json"), encoding="utf-8"))
wd = json.load(open(os.path.join(ROUND, "WORLD.json"), encoding="utf-8"))
STUBS = {
    "correction_to_own_earlier_claim": "loyalty-and-retention",
    "CORRECTION_to_F28": "ranking-and-comparison",
    "method_correction": "method",
    "F71_AIRCOVER_IS_NOT_SHOWN_AT_THE_DECISION_REFUTES_PRIOR_CLAIM": "price-honesty",
}
theme_of = {c["id"]: c["theme"] for c in wd["chunks"]}
theme_of.update(STUBS)

rows, counts = [], collections.Counter()
for f in ci["findings"]:
    fid, filed = f["id"], theme_of.get(f["id"])
    named = themes_named_in(fid)
    if not named:
        verdict = "unknown"          # the id names no theme; this check cannot speak
    elif filed in named:
        verdict = "agrees"           # id names the theme it is filed under
    else:
        verdict = "CONTRADICTS"      # id names other themes and not its own
    counts[verdict] += 1
    rows.append({"id": fid, "competitor": f["competitor"], "filed_theme": filed,
                 "themes_named_in_id": sorted(named), "verdict": verdict})

contra = [r for r in rows if r["verdict"] == "CONTRADICTS"]

# The specific consequence design-critic found, restated as a measurement.
disruption_named = [r for r in rows if "disruption-and-protection" in r["themes_named_in_id"]]
disruption_filed = [r for r in rows if r["filed_theme"] == "disruption-and-protection"]
mismatch = [r["id"] for r in disruption_named if r["filed_theme"] != "disruption-and-protection"]

out = {
  "$comment": "GENERATED by phase0b-theme-audit.py — never hand-edited.",
  "generated": datetime.date.today().isoformat(),
  "rule": "Compares two fields already in the record — a finding's theme and its own id. "
          "Never reads claim prose. Never re-themes anything. Produces a LOWER BOUND: a "
          "mis-filed finding whose id names no theme is counted 'unknown', not 'agrees'.",
  "counts": dict(counts),
  "total": sum(counts.values()),
  "contradiction_rate_of_speakable_rows": (
      round(len(contra) / max(counts["agrees"] + counts["CONTRADICTS"], 1), 4)),
  "disruption_case": {
      "ids_whose_own_id_names_disruption": [r["id"] for r in disruption_named],
      "rows_filed_under_disruption-and-protection": [r["id"] for r in disruption_filed],
      "named_disruption_but_filed_elsewhere": mismatch,
  },
  "contradictions": contra,
  "rows": rows,
}
json.dump(out, open(os.path.join(HERE, "theme-audit.json"), "w", encoding="utf-8"),
          indent=2, ensure_ascii=False)

print("verdicts: " + " · ".join(f"{v} {k}" for k, v in counts.most_common()))
print(f"contradiction rate among rows this check can speak about: "
      f"{out['contradiction_rate_of_speakable_rows']:.1%}")
print(f"\nids naming disruption: {len(disruption_named)} · "
      f"filed under disruption: {len(disruption_filed)} · "
      f"named-but-filed-elsewhere: {len(mismatch)}")
for m in mismatch:
    print("   !", m)
print("\nfirst contradictions:")
for r in contra[:8]:
    print(f"   {r['id'][:52]:<52} filed={r['filed_theme']:<26} id names={r['themes_named_in_id']}")
