import http from "node:http";
const g=p=>new Promise(r=>http.request({host:"localhost",port:9333,path:p},x=>{let d="";x.on("data",c=>d+=c);x.on("end",()=>r(JSON.parse(d)))}).end());
const t=(await g("/json/list")).find(x=>x.type==="page");
const ws=new WebSocket(t.webSocketDebuggerUrl); await new Promise(r=>ws.onopen=r);
let i=0,p=new Map(); ws.onmessage=e=>{const m=JSON.parse(e.data); if(p.has(m.id)){p.get(m.id)(m);p.delete(m.id)}};
const s=(me,pa={})=>new Promise(r=>{const n=++i;p.set(n,r);ws.send(JSON.stringify({id:n,method:me,params:pa}))});
await s("Page.enable");
await s("Page.navigate",{url:"file://"+process.cwd()+"/luma-competitor-research-findings.html"});
await new Promise(r=>setTimeout(r,2200));
const r=await s("Runtime.evaluate",{expression:process.argv[2],returnByValue:true});
console.log(JSON.stringify(r.result.result.value,null,1)); ws.close(); process.exit(0);
