#!/usr/bin/env python3
"""Author the four missing token axes: spacing, typography, elevation, motion —
plus the two density registers (stage, document).

Follows `validation/reports/2026-08-28__token-axes-proposal.md`, which is the plan
(promoted out of gitignored scratch/ on 2026-08-28 so the reasoning survives a clean);
this script is the execution of it. Per-axis provenance, restated here so a
reader doesn't have to open the proposal to know what is transcribed versus
authored:

  SPACING     — TRANSCRIBED verbatim from @carbon/layout 11.58.0's own compiled
                output (`scss/generated/_spacing.scss`, machine-generated by
                Carbon's own build). 13 steps, 0.125rem -> 10rem. Only the DTCG
                `dimension` wrapper is new; the 13 numbers are Carbon's, not
                ours. NOTE: component-index.json's `spacing-scale` component
                was extended from 10 to 13 steps on 2026-08-28 to match. This
                script imports all 13 and FLAGS the mismatch — it does not
                touch component-index.json to resolve it (out of scope).

  TYPOGRAPHY  — MIXED, per brand.md §4 (Anek Latin, OQ-2 resolved 2026-08-27):
      * family   — AUTHORED per brand.md. TWO primitives, because there are two
                    actual typefaces: `sans` (Anek Latin, OQ-2 2026-08-27) and
                    `mono` (Source Code Pro, ART-007, 2026-08-28). Deliberately
                    NO display/body split at this layer — those are roles, and
                    typography.scale.* already expresses them. An earlier pass
                    carried the role down here and produced two leaves holding a
                    byte-identical stack; audit-contracts.py flagged it as a
                    value reachable by two names. Real fallback stacks attached.
      * size     — AUTHORED curated stopping points (7 steps), not Carbon's
                    23-step compiled-formula ramp. brand.md wants one scale at
                    two densities, not a long undifferentiated ramp. Step 07
                    (3.875rem = 62px) is the evidenced display size
                    [ART-005 § Type].
      * weight   — MIXED. light/regular/semibold (300/400/600) are TRANSCRIBED
                    from @carbon/type 11.66.0's compiled `fontWeights` export.
                    heavy (700) and black (800) are AUTHORED — brand.md's
                    evidenced display weight is 700 ("heavy"); Carbon has no
                    value above 600.
      * tracking — AUTHORED, and explicitly a CURVE, not a constant. Only ONE
                    point is evidenced: -0.125rem (-2px) at 62px / step 07
                    [ART-005 § Type]. Every other step is this script's own
                    interpolation (tightens through the scale, crossing to
                    negative around body size rather than Carbon's own table,
                    which stays at 0 tracking until ~92px — see proposal §3).
                    NEEDS VISUAL TESTING before being treated as final; only
                    step 07's value is evidenced.
      * scale    — AUTHORED bundles (composite $type "typography"): one leaf
                    token per named level (display, h1, h2, h3, body, body-sm,
                    caption, code — the exact 8 names component-index.json's
                    `type-scale` component already declares), each a $value
                    object whose four fields are alias strings only, never
                    literals.

  TABULAR FIGURES (brand.md §4, binding) — DTCG has no `font-variant-numeric`
      $type. Mechanism used here, stated explicitly because a rule nothing
      carries is not a rule: every `typography.scale.<level>` leaf token
      carries `$extensions.coforge.fontVariantNumeric: "tabular-nums"`,
      attached to all 8 levels (any of them can carry a number — captions
      label figures, code is often numeric, and "display" covers the stage
      register's "key figures" per brand.md §2). Anything that consumes a
      scale level is expected to read and apply this extension.

  ELEVATION   — geometry AUTHORED, colour ALIASED (not duplicated).
      `semantic.shadow` / `semantic-dark.shadow` already exist and are
      correct; this script does not touch them. The one new primitive
      (`elevation.shadow.raised`) points its `color` field at
      `{semantic.shadow}` and supplies the geometry — Carbon's own numbers
      (2px y-offset, 6px blur, per `@carbon/styles`' hardcoded Sass mixin,
      the only artefact that exists — Carbon ships no DTCG shadow token at
      all) as a STARTING POINT, NOT AN IMPORT (no such token exists upstream
      to import). NEEDS VISUAL CONFIRMATION against the brand's warmer, softer
      language before being treated as final. brand.md §2: a single soft
      shadow, never more than one depth — hence exactly two states (`none`,
      `raised`), no depth ladder. Dark-theme shadow geometry (a parallel
      primitive aliasing `{semantic-dark.shadow}`) is NOT authored here —
      out of scope for this pass.

  MOTION      — TRANSCRIBED verbatim from @carbon/motion 11.51.0's own
                published DTCG (`src/dtcg/motion.json` — this is the one axis
                Carbon ships as native, schema-validated DTCG). Six durations
                (70-700ms), six cubicBezier curves under standard/entrance/exit
                x productive/expressive. At the semantic layer
                (`motion.transition.*`), only the `productive` family is
                aliased, per brand.md §5 ("motion confirms; it does not
                perform"). `expressive` is mirrored into the primitive layer
                (imported, present) but deliberately never aliased into
                anything semantic.

  DENSITY     — AUTHORED per brand.md §2: stage and document "differ in space
                and type scale only, never in colour role or shape language."
                Implemented as two *subsets* pointing at the one shared
                `typography.scale` group and the one shared `spacing` group —
                no duplicated scale, no duplicated spacing ladder. Each
                register's `type-scale` entry uses a non-standard DTCG $type,
                `coforge.levelSet` ($value: an array of pure alias strings) —
                the same kind of documented, structurally-valid, non-spec
                composite Carbon itself uses for its own `transition` $type
                (see proposal §1). It is not a DTCG-standard type; it is
                declared here so nobody mistakes it for one.

THE BINDING CONTRACT
---------------------
Exactly one layer holds literals; everything above it aliases — restated for
every new axis:

    PRIMITIVE (literals allowed)   SEMANTIC (aliases ONLY, recursively —
                                    including inside composite $value dicts
                                    and $value arrays; zero literals, anywhere)
    spacing.*                      (none — spacing has no semantic layer)
    typography.size.*              typography.scale.*
    typography.weight.*
    typography.tracking.*
    typography.family.*
    elevation.shadow.*             elevation.surface.*
    motion.duration.*              motion.transition.*
    motion.easing.*
    (existing) palette.*           (existing) semantic.* / semantic-dark.*
                                    density.*  (aliases spacing.* + typography.scale.*)

A node with `$value` never has non-`$` children (no token nested inside a
token) — the exact defect this repo already found and fixed once in
`semantic-dark` (see flatten-dark-tokens.py). Composite tokens here (the
`typography` and `shadow` $types, and the custom `coforge.levelSet` $type)
avoid this by keeping every sub-field INSIDE the `$value` object/array itself,
never as a sibling JSON key.

SAFETY
------
Refuses to write unless every check passes:
  · zero literals outside primitive groups (walks into composite $value
    dicts/arrays, not just top-level scalars)
  · every alias in the WHOLE file resolves to a real token path (existing
    bare-name palette convention — "{white.default}" meaning
    "palette.white.default" — is preserved for old data; new axes use fully
    qualified paths throughout, exactly as the proposal specifies)
  · no node carries both $value and non-$ children, anywhere in the file
  · existing palette / semantic / semantic-dark are byte-identical to before
  · valid JSON; every leaf token ($value present) has $type

Idempotent: the four axes + density are rebuilt deterministically from this
script's own fixed source data every run, then assigned wholesale onto the
document — running it twice produces byte-identical output both times.

    python3 validation/build-token-axes.py            # check only, writes nothing
    python3 validation/build-token-axes.py --apply    # verify, then write
"""
import json, os, sys, copy

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "design-system", "tokens", "tokens.json")

PRESERVE_GROUPS = ("palette", "semantic", "semantic-dark")

# Primitive-layer path prefixes: literals are permitted here, and ONLY here.
PRIMITIVE_ROOTS = (
    "palette",
    "spacing",
    "typography.size",
    "typography.weight",
    "typography.tracking",
    "typography.family",
    "elevation.shadow",
    "motion.duration",
    "motion.easing",
)


# ---------------------------------------------------------------------------
# axis builders — each returns a plain dict, no I/O, fully deterministic
# ---------------------------------------------------------------------------

def dim(value, unit="rem"):
    return {"value": value, "unit": unit}


def build_spacing():
    """13 steps, transcribed verbatim from @carbon/layout 11.58.0
    scss/generated/_spacing.scss (Carbon's own machine-generated build
    output). component-index.json's spacing-scale was extended to 13 to match,
    2026-08-28 — the contract is now exact."""
    steps = [
        ("01", 0.125), ("02", 0.25), ("03", 0.5), ("04", 0.75), ("05", 1),
        ("06", 1.5), ("07", 2), ("08", 2.5), ("09", 3), ("10", 4),
        ("11", 5), ("12", 6), ("13", 10),
    ]
    out = {
        "$extensions": {"coforge": {"complete_scale":
            "A complete imported ladder. A layout consumes steps directly by name, so "
            "most steps are never aliased by a semantic token and that is the scale "
            "working as intended — unlike colour, spacing has no role layer between the "
            "primitive and the surface."}},
        "$description": "Structural spacing scale. Transcribed from @carbon/layout "
                         "11.58.0 (Apache-2.0) — no brand signal opposes a different "
                         "cadence (token-axes-proposal.md §2). 13 steps; "
                         "component-index.json's spacing-scale component currently "
                         "was extended to 13 on 2026-08-28; the contract is exact. "
                         "script imports faithfully and flags, not resolves.",
    }
    for key, rem in steps:
        out[key] = {
            "$type": "dimension",
            "$value": dim(rem),
            "$description": f"Carbon spacing-{key} — {rem}rem.",
            "$extensions": {"coforge": {"source": "@carbon/layout@11.58.0", "transcribed": True}},
        }
    return out


def build_typography():
    # --- size: authored curated stopping points, not Carbon's 23-step ramp ---
    size_steps = [
        ("01", 0.75, "12px — caption, code."),
        ("02", 0.875, "14px — body-sm."),
        ("03", 1, "16px — body. The tracking curve's zero-crossing lives near here."),
        ("04", 1.25, "20px — h3."),
        ("05", 1.75, "28px — h2."),
        ("06", 2.5, "40px — h1."),
        ("07", 3.875, "62px — display. Evidenced size [ART-005 § Type]."),
    ]
    size = {
        "$description": "Curated stopping points, not Carbon's 23-step compiled-formula "
                         "ramp (brand.md §4: one scale, used at two densities, not a "
                         "long undifferentiated ramp). AUTHORED.",
    }
    for key, rem, note in size_steps:
        size[key] = {
            "$type": "dimension",
            "$value": dim(rem),
            "$description": note,
        }

    # --- weight: 300/400/600 transcribed, 700/800 authored (brand needs 700+) ---
    weight = {
        "$description": "light/regular/semibold transcribed from @carbon/type 11.66.0's "
                         "compiled fontWeights export. heavy/black are CoForge-authored — "
                         "Carbon's ceiling is 600; brand.md §4 evidences a 700 display "
                         "weight and requires weight, not size, to carry hierarchy.",
        "$extensions": {"coforge": {"complete_scale":
            "An authored range, not a used-subset. brand.md §4 makes weight the primary "
            "carrier of hierarchy, so the range has to exist before every rung is spent — "
            "a scale that only contains what today's eight levels happen to use cannot "
            "absorb a ninth without a token change. light (300) and black (800) are "
            "currently unaliased and that is the intended state; Anek Latin serves the "
            "full 100-800 range."}},
        "light": {"$type": "fontWeight", "$value": 300,
                  "$description": "Transcribed from @carbon/type@11.66.0.",
                  "$extensions": {"coforge": {"source": "@carbon/type@11.66.0", "transcribed": True}}},
        "regular": {"$type": "fontWeight", "$value": 400,
                    "$description": "Transcribed from @carbon/type@11.66.0.",
                    "$extensions": {"coforge": {"source": "@carbon/type@11.66.0", "transcribed": True}}},
        "semibold": {"$type": "fontWeight", "$value": 600,
                     "$description": "Transcribed from @carbon/type@11.66.0.",
                     "$extensions": {"coforge": {"source": "@carbon/type@11.66.0", "transcribed": True}}},
        "heavy": {"$type": "fontWeight", "$value": 700,
                  "$description": "AUTHORED. Evidenced display weight [ART-005 § Type] — "
                                   "\"set at heavy weight (700)\". Carbon has no value here."},
        "black": {"$type": "fontWeight", "$value": 800,
                  "$description": "AUTHORED headroom, not currently used by any "
                                   "typography.scale level. Anek Latin serves weights to "
                                   "800 (brand.md §4); reserved for a future display need."},
    }

    # --- tracking: a curve, paired 1:1 with size steps. Only 07 is evidenced. ---
    tracking_steps = [
        ("01", 0.01, "AUTHORED interpolation — slightly open at small size, per "
                      "brand.md §4's \"relaxes to normal or slightly open at small "
                      "sizes.\" NOT evidenced. Needs visual testing."),
        ("02", 0.005, "AUTHORED interpolation. NOT evidenced. Needs visual testing."),
        ("03", 0, "AUTHORED interpolation — the curve's zero-crossing, placed at body "
                   "size deliberately earlier than Carbon's own table (which stays at "
                   "0 until ~92px; proposal §3). NOT evidenced. Needs visual testing."),
        ("04", -0.015, "AUTHORED interpolation. NOT evidenced. Needs visual testing."),
        ("05", -0.03, "AUTHORED interpolation. NOT evidenced. Needs visual testing."),
        ("06", -0.06, "AUTHORED interpolation. NOT evidenced. Needs visual testing."),
        ("07", -0.125, "EVIDENCED [ART-005 § Type] — \"-0.125rem (-2px) tracking at "
                        "62px.\" The only evidenced point on this curve; every other "
                        "step is this script's interpolation toward it."),
    ]
    tracking = {
        "$description": "A curve, not a constant (brand.md §4). Paired 1:1 by index "
                         "with typography.size — tightens as size grows. Only step 07 "
                         "is evidenced; steps 01-06 are AUTHORED interpolation and NEED "
                         "VISUAL TESTING before being treated as final.",
    }
    for key, rem, note in tracking_steps:
        tracking[key] = {"$type": "dimension", "$value": dim(rem), "$description": note}

    # --- family: OQ-2 resolved — Anek Latin, single family, display and body ---
    anek_stack = ["Anek Latin", "-apple-system", "BlinkMacSystemFont", "Segoe UI",
                  "Roboto", "Helvetica Neue", "Arial", "sans-serif"]
    mono_stack = ["Source Code Pro", "ui-monospace", "SFMono-Regular", "Menlo",
                  "Consolas", "Liberation Mono", "monospace"]
    family = {
        "$description": "AUTHORED per brand.md §4 (OQ-2 resolved 2026-08-27: Anek Latin; "
                         "mono added 2026-08-28). Two primitives, because there are two "
                         "actual typefaces. There is deliberately no display/body split "
                         "here: 'display' and 'body' are ROLES, and roles live at the "
                         "semantic layer where typography.scale.* already expresses them "
                         "by which level draws which family. Carrying the role down into "
                         "the primitive layer produced two leaves holding a byte-identical "
                         "stack — a value reachable by two names, which is the same defect "
                         "CoForge refused to inherit from coforge.com. If display and body "
                         "ever diverge, add a third primitive and repoint the affected "
                         "scale levels; the levels are where that decision belongs.",
        "sans": {"$type": "fontFamily", "$value": anek_stack,
                 "$description": "Anek Latin. Every non-code level: display, h1, h2, h3, "
                                  "body, body-sm, caption. CoForge is single-family for "
                                  "prose (brand.md §4)."},
        "mono": {"$type": "fontFamily", "$value": mono_stack,
                 "$description": "Code and token values. Source Code Pro, selected on "
                                  "measurement [ART-007 § Optical pairing] — its x-height "
                                  "ratio is 0.486 against Anek Latin's 0.488, a 0.4% "
                                  "difference. Inline code sits inside body text, so a "
                                  "mismatched x-height reads as a size change mid-sentence "
                                  "and invites a compensating size nudge that then breaks "
                                  "alignment in tables. The nearest rival was 14x further "
                                  "off. Not a brand gesture — a face chosen to be "
                                  "unnoticeable next to the one that is."},
    }

    tabular_ext = {
        "coforge": {
            "fontVariantNumeric": "tabular-nums",
            "reason": "Anek Latin's digits are proportional by default — a '1' measures "
                      "7.7% narrower than a '0' [ART-006 § The finding that decides it]. "
                      "DTCG has no font-variant-numeric $type, so this is carried as an "
                      "extension. Binding per brand.md §4: tabular figures are not a "
                      "per-screen choice — anything consuming this scale level MUST "
                      "apply font-variant-numeric: tabular-nums; proportional figures "
                      "are the exception a designer must ask for.",
        }
    }

    def scale_level(family_key, size_key, weight_key, tracking_key, note):
        return {
            "$type": "typography",
            "$value": {
                "fontFamily": f"{{typography.family.{family_key}}}",
                "fontSize": f"{{typography.size.{size_key}}}",
                "fontWeight": f"{{typography.weight.{weight_key}}}",
                "letterSpacing": f"{{typography.tracking.{tracking_key}}}",
            },
            "$description": note,
            "$extensions": tabular_ext,
        }

    scale = {
        "$description": "AUTHORED. The only 8 names component-index.json's type-scale "
                         "component declares. Composite $type 'typography' — every "
                         "field inside $value is an alias string, never a literal. "
                         "Every level carries the tabular-figures extension (see "
                         "family/$description above and each level's $extensions).",
        "display": scale_level("sans", "07", "heavy", "07",
                                "Stage register hero / key figures. Evidenced size and "
                                "tracking [ART-005 § Type]."),
        "h1": scale_level("sans", "06", "heavy", "06",
                           "Weight carries hierarchy before size (brand.md §4)."),
        "h2": scale_level("sans", "05", "semibold", "05", "AUTHORED."),
        "h3": scale_level("sans", "04", "semibold", "04", "AUTHORED."),
        "body": scale_level("sans", "03", "regular", "03",
                             "The document register's working text. Most of CoForge's "
                             "L1 output is this level (ADR-012)."),
        "body-sm": scale_level("sans", "02", "regular", "02", "AUTHORED."),
        "caption": scale_level("sans", "01", "regular", "01", "AUTHORED."),
        "code": scale_level("mono", "01", "regular", "03",
                             "Source Code Pro at the caption size step. Tracking is "
                             "reset to the curve's zero-crossing (03) rather than "
                             "caption's slightly-open 01: a monospace face already "
                             "carries its own fixed advance, and adding letter-spacing "
                             "on top widens an already-wide face and breaks the column "
                             "alignment that is the whole reason code is monospaced."),
    }

    return {
        "$description": "Typography primitives + semantic scale. AUTHORED per "
                         "brand.md §4 (OQ-2 resolved: Anek Latin). Not a Carbon import "
                         "— see this script's module docstring for the per-field "
                         "provenance breakdown.",
        "size": size,
        "weight": weight,
        "tracking": tracking,
        "family": family,
        "scale": scale,
    }


def build_elevation():
    shadow = {
        "$description": "Geometry AUTHORED (nothing exists upstream to import — Carbon "
                         "ships zero DTCG shadow tokens; the only artefact is one line "
                         "of hardcoded Sass). Colour ALIASED from the existing, correct "
                         "semantic.shadow — not duplicated. brand.md §2: a single soft "
                         "shadow, never more than one depth — hence exactly two states.",
        "none": {
            "$type": "shadow",
            "$value": [],
            "$description": "No shadow — DTCG's documented way to express zero shadow "
                             "layers. Used by flat surfaces.",
        },
        "raised": {
            "$type": "shadow",
            "$value": {
                "color": "{semantic.shadow}",
                "offsetX": dim(0, "px"),
                "offsetY": dim(2, "px"),
                "blur": dim(6, "px"),
                "spread": dim(0, "px"),
            },
            "$description": "Single soft shadow (brand.md §2 — never more than one "
                             "depth at a time). Geometry (2px/6px) is Carbon's own "
                             "number (@carbon/styles box-shadow mixin) used as a "
                             "STARTING POINT, NOT AN IMPORT — no such token exists "
                             "upstream. NEEDS VISUAL CONFIRMATION against the brand's "
                             "warmer, softer language before being treated as final. "
                             "Colour aliases the existing semantic.shadow (light theme) "
                             "— a parallel dark-theme geometry primitive is not "
                             "authored here.",
        },
    }
    surface = {
        "$description": "The only layer card's `elevation` variant "
                         "(component-index.json) may read. Pure aliases onto "
                         "elevation.shadow.",
        "flat": {"$type": "shadow", "$value": "{elevation.shadow.none}",
                 "$description": "AUTHORED."},
        "raised": {"$type": "shadow", "$value": "{elevation.shadow.raised}",
                   "$description": "AUTHORED."},
    }
    return {
        "$description": "Elevation geometry (authored) + the existing shadow colour "
                         "(aliased, not duplicated). See build_elevation() docstring "
                         "notes in this script for the visual-confirmation flag.",
        "shadow": shadow,
        "surface": surface,
    }


def build_motion():
    """Transcribed verbatim from @carbon/motion 11.51.0's src/dtcg/motion.json —
    the one axis Carbon ships as native, schema-validated DTCG. Fetched and
    read in full against the published npm tarball (registry dist.tarball),
    2026-08-27."""
    duration = {
        "$description": "Transcribed from @carbon/motion@11.51.0 src/dtcg/motion.json. "
                         "Unopinionated and structural — no brand signal opposes it.",
        "$extensions": {"coforge": {"complete_scale":
            "A complete imported ladder, like palette. Rungs are aliased as transitions "
            "need them; an unaliased rung is available headroom, not dead weight. Do not "
            "prune to the currently-used subset — that trades a stable scale for churn "
            "every time a new transition is named."}},
        "fast": {
            "01": {"$type": "duration", "$value": dim(70, "ms"),
                   "$description": "Micro-interactions such as button and toggle."},
            "02": {"$type": "duration", "$value": dim(110, "ms"),
                   "$description": "Micro-interactions such as fade in."},
        },
        "moderate": {
            "01": {"$type": "duration", "$value": dim(150, "ms"),
                   "$description": "Default transition speed."},
            "02": {"$type": "duration", "$value": dim(240, "ms"),
                   "$description": "Expansion, system communication, toast."},
        },
        "slow": {
            "01": {"$type": "duration", "$value": dim(400, "ms"),
                   "$description": "Large expansion, important system notifications."},
            "02": {"$type": "duration", "$value": dim(700, "ms"),
                   "$description": "Background dimming, large hero transitions."},
        },
    }
    easing = {
        "$description": "Transcribed from @carbon/motion@11.51.0 src/dtcg/motion.json. "
                         "All 6 control points sit within [0,1] on both axes — no "
                         "overshoot, no bounce, consistent with brand.md §5.",
        "$extensions": {"coforge": {"complete_scale":
            "Both Carbon families are mirrored; only `productive` is aliased by "
            "motion.transition.*. The `expressive` curves are deliberately present and "
            "deliberately unreachable — brand.md §5 rules that motion confirms rather "
            "than performs, and Carbon documents `expressive` as built to be noticed. "
            "Mirroring rather than deleting keeps the import a faithful copy, so a future "
            "decision to admit them is an aliasing choice, not a re-import."}},
        "standard": {
            "productive": {"$type": "cubicBezier", "$value": [0.2, 0, 0.38, 0.9],
                           "$description": "UI elements that move within the viewport."},
            "expressive": {"$type": "cubicBezier", "$value": [0.4, 0.14, 0.3, 1],
                           "$description": "Mirrored, not aliased by any CoForge "
                                            "semantic transition — brand.md §5."},
        },
        "entrance": {
            "productive": {"$type": "cubicBezier", "$value": [0, 0, 0.38, 0.9],
                           "$description": "Elements entering the screen."},
            "expressive": {"$type": "cubicBezier", "$value": [0, 0, 0.3, 1],
                           "$description": "Mirrored, not aliased — brand.md §5."},
        },
        "exit": {
            "productive": {"$type": "cubicBezier", "$value": [0.2, 0, 1, 0.9],
                           "$description": "Elements leaving the screen."},
            "expressive": {"$type": "cubicBezier", "$value": [0.4, 0.14, 1, 1],
                           "$description": "Mirrored, not aliased — brand.md §5."},
        },
    }
    transition = {
        "$description": "AUTHORED naming, aliasing only the productive family "
                         "(brand.md §5: motion confirms, it does not perform). "
                         "expressive exists in the primitive layer above but is "
                         "never referenced here.",
        "reveal": {
            "duration": {"$type": "duration", "$value": "{motion.duration.moderate.01}"},
            "easing": {"$type": "cubicBezier", "$value": "{motion.easing.entrance.productive}"},
            "$description": "Something new becoming present.",
        },
        "dismiss": {
            "duration": {"$type": "duration", "$value": "{motion.duration.moderate.01}"},
            "easing": {"$type": "cubicBezier", "$value": "{motion.easing.exit.productive}"},
            "$description": "Something leaving.",
        },
        "confirm": {
            "duration": {"$type": "duration", "$value": "{motion.duration.fast.02}"},
            "easing": {"$type": "cubicBezier", "$value": "{motion.easing.standard.productive}"},
            "$description": "A short, level acknowledgement of an action.",
        },
    }
    return {
        "$description": "Motion primitives, transcribed from Carbon's own native "
                         "DTCG. Semantic transitions alias the productive family only.",
        "duration": duration,
        "easing": easing,
        "transition": transition,
    }


def build_density():
    """AUTHORED. Subsets/defaults over the one shared typography.scale and
    spacing groups — brand.md §2: stage and document "differ in space and
    type scale only, never in colour role or shape language." No scale or
    spacing ladder is duplicated."""
    def level_set(levels, note):
        return {
            "$type": "coforge.levelSet",
            "$value": [f"{{typography.scale.{lvl}}}" for lvl in levels],
            "$description": note,
            "$extensions": {
                "coforge": {
                    "note": "Non-standard DTCG $type — an array of pure alias strings, "
                            "the same documented-extension shape Carbon itself uses "
                            "for its own 'transition' $type. Not a DTCG-spec type.",
                }
            },
        }

    stage = {
        "type-scale": level_set(
            ["display", "h1", "h2", "h3", "body"],
            "Covers, section openers, key figures — large type, long silences "
            "(brand.md §2). Withholds body-sm/caption/code.",
        ),
        "spacing-unit": {
            "$type": "dimension",
            "$value": "{spacing.07}",
            "$description": "One unit at stage density.",
        },
        "$description": "Stage register.",
    }
    document = {
        "type-scale": level_set(
            ["h2", "h3", "body", "body-sm", "caption", "code"],
            "The working body of a report, table, scorecard or spec — tight, "
            "legible, scannable (brand.md §2). Withholds display/h1.",
        ),
        "spacing-unit": {
            "$type": "dimension",
            "$value": "{spacing.03}",
            "$description": "One unit at document density — tighter default.",
        },
        "$description": "Document register.",
    }
    return {
        "$description": "AUTHORED. Two named registers, no new primitives — subsets "
                         "of the one shared typography.scale and spacing group "
                         "(brand.md §2).",
        "stage": stage,
        "document": document,
    }


# ---------------------------------------------------------------------------
# generic tree walkers
# ---------------------------------------------------------------------------

def leaves(node, path, out):
    """Every token, by dotted path. Descends INTO tokens that also have
    children — returning early here is exactly the bug that hid the
    semantic-dark hybrid-node defect (see flatten-dark-tokens.py)."""
    if not isinstance(node, dict):
        return
    if "$value" in node:
        out.append((path, node))
    for k, v in node.items():
        if k.startswith("$"):
            continue
        leaves(v, f"{path}.{k}" if path else k, out)


def hybrids(doc):
    out = []

    def walk(node, path):
        if not isinstance(node, dict):
            return
        if "$value" in node and [k for k in node if not k.startswith("$")]:
            out.append(path)
        for k, v in node.items():
            if not k.startswith("$"):
                walk(v, f"{path}.{k}" if path else k)

    for grp in doc:
        if not grp.startswith("$"):
            walk(doc[grp], grp)
    return out


def all_leaves(doc):
    out = []
    for grp in doc:
        if grp.startswith("$"):
            continue
        leaves(doc[grp], grp, out)
    return out


def is_primitive(path):
    return any(path == r or path.startswith(r + ".") for r in PRIMITIVE_ROOTS)


def pure_alias(value):
    """True iff value contains ONLY alias strings — recursively through
    dicts (composite $value objects) and lists (levelSet arrays). A single
    non-alias scalar anywhere inside fails it."""
    if isinstance(value, str):
        return value.startswith("{") and value.endswith("}")
    if isinstance(value, list):
        return all(pure_alias(v) for v in value)
    if isinstance(value, dict):
        return all(pure_alias(v) for v in value.values())
    return False


def find_literal_leaks(doc):
    bad = []
    for path, node in all_leaves(doc):
        if is_primitive(path):
            continue
        if not pure_alias(node.get("$value")):
            bad.append((path, node.get("$value")))
    return bad


def find_unresolved_aliases(doc):
    known = {p for p, _ in all_leaves(doc)}

    def resolves(target):
        if target in known:
            return True
        # existing bare-name convention: "{white.default}" == palette.white.default
        return any(f"{g}.{target}" in known for g in PRESERVE_GROUPS)

    bad = []

    def walk(value, path):
        if isinstance(value, str) and value.startswith("{"):
            target = value.strip("{}")
            if not resolves(target):
                bad.append((path, value))
        elif isinstance(value, list):
            for v in value:
                walk(v, path)
        elif isinstance(value, dict):
            for k, v in value.items():
                walk(v, f"{path}.{k}")

    for path, node in all_leaves(doc):
        walk(node.get("$value"), path)
    return bad


def find_missing_type(doc):
    return [path for path, node in all_leaves(doc) if "$type" not in node]


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    apply = "--apply" in sys.argv
    original = json.load(open(TOKENS))

    preserved_before = {g: copy.deepcopy(original[g]) for g in PRESERVE_GROUPS}

    candidate = dict(original)
    candidate["spacing"] = build_spacing()
    candidate["typography"] = build_typography()
    candidate["elevation"] = build_elevation()
    candidate["motion"] = build_motion()
    candidate["density"] = build_density()

    ok = True

    # 1. zero literals outside primitive groups
    leaks = find_literal_leaks(candidate)
    if leaks:
        print(f"  FAIL {len(leaks)} literal(s) outside primitive groups")
        for p, v in leaks[:10]:
            print(f"      {p} -> {v!r}")
        ok = False
    else:
        print("  zero literals outside primitive groups")

    # 2. every alias resolves
    bad = find_unresolved_aliases(candidate)
    if bad:
        print(f"  FAIL {len(bad)} unresolved alias(es)")
        for p, v in bad[:10]:
            print(f"      {p} -> {v}")
        ok = False
    else:
        print("  every alias resolves")

    # 3. no node carries both $value and non-$ children
    hyb = hybrids(candidate)
    if hyb:
        print(f"  FAIL {len(hyb)} hybrid node(s) (token nested inside a token)")
        for p in hyb[:10]:
            print(f"      {p}")
        ok = False
    else:
        print("  no node carries both $value and child tokens")

    # 4. palette/semantic/semantic-dark byte-identical
    preserve_ok = True
    for g in PRESERVE_GROUPS:
        if candidate[g] != preserved_before[g]:
            print(f"  FAIL {g} was modified")
            preserve_ok = False
    if preserve_ok:
        print(f"  {', '.join(PRESERVE_GROUPS)} unchanged")
    else:
        ok = False

    # 5. every leaf has $type (valid JSON is implicit — we built it as a dict)
    missing = find_missing_type(candidate)
    if missing:
        print(f"  FAIL {len(missing)} leaf(ves) missing $type")
        for p in missing[:10]:
            print(f"      {p}")
        ok = False
    else:
        print("  every leaf token has $type and $value")

    # counts + flags, informational
    n_leaves_before = len(all_leaves(original))
    n_leaves_after = len(all_leaves(candidate))
    print(f"\n  leaves before: {n_leaves_before}  after: {n_leaves_after}  "
          f"(+{n_leaves_after - n_leaves_before})")
    print("  NOTE: spacing imports all 13 Carbon steps; component-index.json's "
          "spacing-scale was extended to 13 on 2026-08-28 — contract now exact.")
    print("  FLAG: typography.tracking steps 01-06 and elevation.shadow.raised's "
          "geometry are authored/starting-point values needing visual testing — "
          "only tracking step 07 (-0.125rem @ 62px) is evidenced.")

    if not ok:
        print("\n  REFUSING TO WRITE")
        return 1

    if not apply:
        print(f"\n  check only — would add spacing, typography, elevation, motion, "
              f"density ({n_leaves_after - n_leaves_before} new leaves). "
              f"Re-run with --apply")
        return 0

    with open(TOKENS, "w") as fh:
        json.dump(candidate, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"\n  WROTE {os.path.relpath(TOKENS, ROOT)} — "
          f"{n_leaves_after - n_leaves_before} new leaves across 4 axes + density")
    return 0


if __name__ == "__main__":
    sys.exit(main())
