#!/usr/bin/env python3
"""Build .ai/index.json + .ai/index.md — the CoForge system index.

Closes the Indexing Layer gap (ADR-008). Agents load this ONCE at session start
instead of re-deriving system structure every time. Generated by scanning; never
hand-edited.

Usage protocol (encoded in the output, and repeated here):
  - Load .ai/index.md once at session start; keep it in context.
  - Fetch full artifact-type / agent / ADR detail on demand from the source files.
  - If a lookup is not in the index, the index is stale: re-run this script.
"""
import json, os, re, datetime, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def P(*a): return os.path.join(ROOT, *a)

def jload(rel, default=None):
    try:
        with open(P(rel)) as f: return json.load(f)
    except Exception: return default

def frontmatter(path):
    txt = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---", txt, re.S)
    if not m: return {}
    d = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            d[k.strip()] = v.strip()
    return d

# ---------- agents ----------
agents = []
adir = P(".claude", "agents")
for fn in sorted(os.listdir(adir)):
    if not fn.endswith(".md"): continue
    fm = frontmatter(os.path.join(adir, fn))
    tools = [t.strip() for t in fm.get("tools", "").strip("[]").split(",") if t.strip()]
    agents.append({
        "name": fm.get("name", fn[:-3]),
        "model": fm.get("model"),
        "tools": tools,
        "writes": bool({"Write", "Edit"} & set(tools)),
        "file": f".claude/agents/{fn}",
        "trigger": fm.get("description", "")[:180],
    })

# ---------- artifact types ----------
types_doc = jload("artifacts/_types.json", {"types": []})
types = types_doc.get("types", [])
by_stage, by_owner = {}, {}
for t in types:
    by_stage.setdefault(t["stage"], []).append(t["type"])
    by_owner.setdefault(t["owner_agent"], []).append(t["type"])

# ---------- ADRs ----------
adrs = []
for fn in sorted(os.listdir(P("decisions"))):
    if not fn.endswith(".md"): continue
    head = open(P("decisions", fn), encoding="utf-8").read()[:600]
    title = (re.search(r"^#\s*(.+)$", head, re.M) or [None, fn])[1]
    status = (re.search(r"\*\*Status:\*\*\s*(.+)$", head, re.M) or [None, "unknown"])[1]
    adrs.append({"file": f"decisions/{fn}", "title": title.strip(), "status": status.strip()})

# ---------- source-of-truth state ----------
ledger = jload("research/evidence-ledger.json", {})
tokens = jload("design-system/tokens/tokens.json", {})
cindex = jload("design-system/component-index.json", {})
registry = jload("artifacts/_registry.json", {})
def _leaves(o):
    if not isinstance(o, dict): return 0
    if "$value" in o: return 1
    return sum(_leaves(v) for k, v in o.items() if not k.startswith("$"))
n_tokens = _leaves(tokens)   # DTCG leaves, counted the same way llms.txt counts them
sources = [f for f in os.listdir(P("research", "sources")) if not f.startswith(".")]

state = {
    # The fork is a DECISION, not a heuristic. L1 primitives existing does not make
    # a design system exist. Declared state wins; counts are reported alongside it.
    "ds_fork": "RED",
    "ds_fork_note": "RED until adapter #1 populates L2 components (ADR-011).",
    "evidence_records": ledger.get("count", 0),
    "raw_sources": len(sources),
    "tokens": n_tokens,
    "components": cindex.get("count", 0),
    "artifacts": registry.get("count", 0),
    "brand_defined": "Status: EMPTY" not in open(P("design-system/foundations/brand.md")).read(),
}

# ---------- relationships ----------
rels = []
for t in types:
    rels.append({"from": t["owner_agent"], "rel": "owns", "to": t["type"]})
    rels.append({"from": t["type"], "rel": "validated-by", "to": t["checklist"]})
    rels.append({"from": t["type"], "rel": "in-stage", "to": t["stage"]})
for a in agents:
    for tool in a["tools"]:
        rels.append({"from": a["name"], "rel": "may-use", "to": tool})

index = {
    "$comment": "GENERATED by validation/index-system.py. Never hand-edit. Re-run after any structural change.",
    "generated_at": datetime.date.today().isoformat(),
    "usage_protocol": [
        "Load .ai/index.md once at session start; keep it in context.",
        "Fetch full detail on demand from the source file named in each entry.",
        "A lookup missing here means the index is stale — re-run validation/index-system.py.",
    ],
    "state": state,
    "counts": {"agents": len(agents), "artifact_types": len(types),
               "adrs": len(adrs), "relationships": len(rels)},
    "agents": agents,
    "artifact_types_by_stage": by_stage,
    "artifact_types_by_owner": by_owner,
    "adrs": adrs,
    "relationships": rels,
}
json.dump(index, open(P(".ai", "index.json"), "w"), indent=2)

# ---------- human / agent-cheap markdown view ----------
L = []
L.append("# CoForge system index\n")
L.append("> GENERATED by `validation/index-system.py`. Never hand-edit.\n")
L.append("> **Load once at session start. Fetch detail on demand. If a lookup is missing here, re-run the script.**\n")
L.append(f"\n{len(agents)} agents · {len(types)} artifact types · {len(adrs)} ADRs · {len(rels)} relationships\n")
L.append("\n## State\n")
L.append("| | |\n|---|---|")
for k, v in state.items(): L.append(f"| {k} | {v} |")
L.append("\n## Agents\n")
L.append("| agent | model | tools | writes |\n|---|---|---|---|")
for a in agents:
    L.append(f"| `{a['name']}` | {a['model']} | {', '.join(a['tools'])} | {'yes' if a['writes'] else 'NO'} |")
L.append("\n## Artifact types by stage\n")
for s, ts in by_stage.items():
    L.append(f"- **{s}** ({len(ts)}): {' · '.join(ts)}")
L.append("\n## Ownership\n")
L.append("| agent | owns |\n|---|---|")
for o, ts in sorted(by_owner.items()):
    L.append(f"| `{o}` | {', '.join(ts)} |")
L.append("\n## Decisions\n")
for a in adrs: L.append(f"- [{a['title']}]({a['file']}) — {a['status']}")
open(P(".ai", "index.md"), "w").write("\n".join(L) + "\n")

print(f"index built: {len(agents)} agents · {len(types)} types · {len(adrs)} ADRs · {len(rels)} relationships")
print(f"  state: DS={state['ds_fork']} evidence={state['evidence_records']} "
      f"tokens={state['tokens']} components={state['components']} artifacts={state['artifacts']}")
