#!/usr/bin/env python3
"""Rebuild artifacts/_registry.json and artifacts/ARTIFACTS.md by scanning artifacts/.

Generated files — never hand-edit either output. Run after any artifact changes.
"""
import json, os, re, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART  = os.path.join(ROOT, "artifacts")
NAME = re.compile(r"^(\d{4}-\d{2}-\d{2})__([a-z0-9-]+)__([a-z0-9-]+)__v(\d+)$")

def main():
    types = {t["type"] for t in json.load(open(os.path.join(ART, "_types.json")))["types"]}
    rows, problems = [], []

    for ws in sorted(os.listdir(ART)):
        wsp = os.path.join(ART, ws)
        if ws.startswith("_") or ws.startswith(".") or not os.path.isdir(wsp):
            continue
        for d in sorted(os.listdir(wsp)):
            dp = os.path.join(wsp, d)
            if not os.path.isdir(dp):
                continue
            m = NAME.match(d)
            if not m:
                problems.append(f"{ws}/{d}: name does not match YYYY-MM-DD__type__slug__vN")
                continue
            date, atype, slug, ver = m.groups()
            if atype not in types:
                problems.append(f"{ws}/{d}: type '{atype}' is not in _types.json")
            mf = os.path.join(dp, "manifest.json")
            if not os.path.exists(mf):
                problems.append(f"{ws}/{d}: no manifest.json")
                continue
            try:
                man = json.load(open(mf))
            except Exception as e:
                problems.append(f"{ws}/{d}: manifest.json unreadable ({e})")
                continue
            if not os.path.exists(os.path.join(dp, "validation.md")):
                problems.append(f"{ws}/{d}: no validation.md — nothing enters artifacts/ unvalidated")
            rows.append({
                "id": man.get("id"), "type": atype, "workstream": ws, "slug": slug,
                "version": int(ver), "date": date, "status": man.get("status"),
                "stage": man.get("stage"), "produced_by": man.get("produced_by"),
                "supersedes": man.get("supersedes"),
                "evidence": (man.get("inputs") or {}).get("evidence", []),
                "tokens_version": (man.get("inputs") or {}).get("tokens_version"),
                "surface": man.get("surface"), "path": f"artifacts/{ws}/{d}",
            })

    json.dump({"$comment": "GENERATED by validation/rebuild-registry.py. Never hand-edit.",
               "generated_at": datetime.date.today().isoformat(),
               "count": len(rows), "artifacts": rows},
              open(os.path.join(ART, "_registry.json"), "w"), indent=2)

    live = [r for r in rows if r["status"] not in ("superseded", "archived")]
    with open(os.path.join(ART, "ARTIFACTS.md"), "w") as f:
        f.write("# Artifacts\n\n> GENERATED by `validation/rebuild-registry.py`. Never hand-edit.\n\n")
        f.write(f"{len(rows)} total · {len(live)} live\n\n")
        if live:
            f.write("| ID | Type | Workstream | v | Status | By | Path |\n|---|---|---|---|---|---|---|\n")
            for r in live:
                f.write(f"| {r['id']} | {r['type']} | {r['workstream']} | {r['version']} "
                        f"| {r['status']} | {r['produced_by']} | `{r['path']}` |\n")
        else:
            f.write("_No artifacts yet._\n")

    print(f"registry rebuilt: {len(rows)} artifact(s), {len(live)} live")
    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print("  -", p)
        sys.exit(1)

if __name__ == "__main__":
    main()
